# Generated by Django 6.0.6 on 2026-06-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_singer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
